@startuml
hide empty methods
hide empty fields
interface "ITaskItem" {
    +content : TaskContentType
    +id : string
    +status : ETaskStatus
    +toggle() : void
}
class "Task" {
    +content : T
    +id : string
    +owner : ITaskOwner | null
    +status : ETaskStatus
    -setStatus(s: ETaskStatus) : void
    +toggle() : void
}
"ITaskItem" <|.. "Task"
@enduml