@startuml
hide empty methods
hide empty fields
interface "ITaskRepository" {
    +createTask(id: string, content: TaskContentType, finishDate: Date | null) : ITaskItem
}
class "TaskRepository" {
    +createTask(id: string, content: TaskContentType, finishDate: Date | null) : ITaskItem
}
"ITaskRepository" <|.. "TaskRepository"
@enduml