@startuml
hide empty methods
hide empty fields
class "TaskOwner" {
    +friends : ITaskOwner[]
    +id : string
    +ownedTasks : ITaskItem[]
}
interface "ITaskOwner" {
    +friends : Array<ITaskOwner>
    +id : string
    +ownedTasks : Array<ITaskItem>
}
"ITaskOwner" <|.. "TaskOwner"
@enduml